
import type { NextPage } from 'next'
import Head from 'next/head'
import { useActions } from '../hooks/useActions'
import { useTypedSelector } from '../hooks/useTypedSelector'
import MainLayout from '../layouts/MainLayouts'

const Index: NextPage = () => {

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <MainLayout>
        <div className='center'>
          <h1>Добро пожаловать</h1>
          <h3>Здесь собраны лучшие треки</h3>
        </div>
      </MainLayout>
      <style jsx>
        {`
          .center{
            display:flex;
            margin-top: 150px;
            flex-direction:column;
            align-items: center;
            justify-content:center;
          }
          `}
      </style>

    </div>
  )
}

export default Index
